spring.application.name=eco-wise-ai-backend
#########################################################
# Server
#########################################################

server.port=8080

#########################################################
# PostgreSQL (Neon Database)
#########################################################

spring.datasource.url=jdbc:postgresql://ep-twilight-flower-aokbyjdu.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_FZBm6p9vAnGM

spring.datasource.driver-class-name=org.postgresql.Driver

#########################################################
# Hikari Connection Pool
#########################################################

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

#########################################################
# JPA / Hibernate
#########################################################

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

#########################################################
# Logging
#########################################################

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

#########################################################
# DevTools
#########################################################

spring.devtools.restart.enabled=true
